/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: markcraig (https://sketchfab.com/markcraig)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/quokka-c0212e29e3c748a5b499dc2d72f2cd84
Title: Quokka
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.31]} scale={0.01}>
        <mesh geometry={nodes.pSphere3_blinn3_0.geometry} material={materials.blinn3} />
        <mesh geometry={nodes.pSphere3_blinn2_0.geometry} material={materials.blinn2} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
