/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Watndit (https://sketchfab.com/Watndit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-sofa-62dbd2a0afb44b21ab43dcc936eb1d65
Title: Wooden Sofa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.75}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={15.5}>
            <mesh geometry={nodes.Cube004_leder_oben_0.geometry} material={materials.leder_oben} />
            <mesh geometry={nodes.Cube004_leder_oben_0_1.geometry} material={materials.leder_oben} />
          </group>
          <mesh geometry={nodes.Cube_rest_0.geometry} material={materials.rest} rotation={[-Math.PI / 2, 0, 0]} scale={15.5} />
          <mesh geometry={nodes.Cube001_rest_0.geometry} material={materials.rest} rotation={[-Math.PI / 2, 0, 0]} scale={15.5} />
          <mesh geometry={nodes.Cube002_rest_0.geometry} material={materials.rest} rotation={[-Math.PI / 2, 0, 0]} scale={15.5} />
          <mesh geometry={nodes.Cube003_rest_0.geometry} material={materials.rest} rotation={[-Math.PI / 2, 0, 0]} scale={15.5} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
