/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: ஜCIHIRISஜ (https://sketchfab.com/crazy4creativity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metalic-millenium-falcon-star-wars-0c09dbb153a44de0826179d04883a1fd
Title: Metalic Millenium Falcon - Star Wars
*/

import { useGLTF } from "@react-three/drei";

export function MilleniumFalcon(props) {
  const { nodes, materials } = useGLTF("assets/Misc/millenium_falcon/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.96, -59.08, -28.65]}
        rotation={[-3.14, -0.03, -0.02]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_1.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_2.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_3.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_4.geometry}
            material={materials.Material0}
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload('assets/Misc/millenium_falcon/scene-transformed.glb')
