/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Qoodrat (https://sketchfab.com/qoodrat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-table-cc60f4bce4fd4af78904b4253e2a3443
Title: Vintage table
*/

import { useGLTF } from '@react-three/drei'

export function HeraTable(props) {
  const { nodes, materials } = useGLTF('assets/Tables/hera_table/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.28, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Gold.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
