/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Matt LeMoine (https://sketchfab.com/Matt_LeMoine)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/lamp-2b14055dc8054ec79b4d0d7e8f00be1e
Title: Lamp
*/

import { useGLTF } from "@react-three/drei";

export function Lamp(props) {
  const { nodes, materials } = useGLTF("assets/lamp/scene-transformed.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[0, 0, -400]}
      rotation={[Math.PI, Math.PI, Math.PI]}
    >
      <group position={[0, -196.27, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.pSphere4_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.pSphere4_lambert5_0.geometry}
              material={materials.lambert5}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/lamp/scene-transformed.glb");

export const LampData = {
  name: "Lamp",
  URL: "assets/lamp/scene-transformed.glb",
  groups: [
    {
      position: [0, 0, -400],
      rotation: [Math.PI, Math.PI, Math.PI],
    },
    {
      position: [0, -196.27, 0],
      rotation: [Math.PI / 2, 0, -Math.PI],
    },
    {
      rotation: [-Math.PI, 0, 0],
    },
    {
      rotation: [Math.PI / 2, 0, 0],
      meshArray: [
        {
          geometry: "pSphere4_lambert1_0",
          material: "lambert1",
        },
        {
          geometry: "pSphere4_lambert5_0",
          material: "lambert5",
        },
      ],
    },
  ],
};
