/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Jamie McFarlane (https://sketchfab.com/jamiemcfarlane)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/victorian-coffee-table-ad38ff95b713412080992a48eab50899
Title: Victorian Coffee Table
*/

import { useGLTF } from "@react-three/drei";

export function VictorianCoffeeTable(props) {
  const { nodes, materials } = useGLTF(
    "assets/victorian_coffee_table/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.initialShadingGroup}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("assets/victorian_coffee_table/scene-transformed.glb");


