/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-acd1cef307b94803846d624b251a4e63
Title: Wooden Table
*/

import { useGLTF } from "@react-three/drei";

export function WoodenTable2(props) {
  const { nodes, materials } = useGLTF(
    "assets/wooden_table_2/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null} position={[0, 0, 0]} rotation={[Math.PI, Math.PI, Math.PI]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Default}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("assets/wooden_table_2/scene-transformed.glb");


