/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: FlukierJupiter (https://sketchfab.com/FlukierJupiter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-0dc1c7d6cbab4d74bef7c4f82abf2caf
Title: Wooden Table
*/
import { useGLTF } from "@react-three/drei";

export function WoodenTable(props) {
  const { nodes, materials } = useGLTF(
    "assets/wooden_table/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.19, -80.98, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.01}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes["Desk_LP_01_-_Default_0"].geometry}
            material={materials["01_-_Default"]}
            position={[-79.35, 0, 51.85]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
