/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Pascal T. Monette (https://sketchfab.com/baltazo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rounded-chair-6a9ed9947c0e499d938563de4920fbf0
Title: Rounded Chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HaloChair(props) {
  const { nodes, materials } = useGLTF(
    "assets/Chairs/halo_chair/scene-transformed.glb"
  );
  return (
    <group
      {...props}
      dispose={null}
      position={[0, 0, -2]}
      rotation={[Math.PI / 0.9, Math.PI, Math.PI]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.07}>
        <mesh
          geometry={nodes.Chair_Back_0.geometry}
          material={materials.Chair_Back}
          position={[0, 0.89, 2.25]}
          rotation={[1.44, 0, 0]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Chair_Sit_0.geometry}
          material={materials.Chair_Back}
          position={[0, 0.43, 1.18]}
          rotation={[-0.08, 0, 0]}
          scale={0.17}
        />
        <mesh
          geometry={nodes.Chair_Legs_0.geometry}
          material={materials.Chair_Legs}
          position={[0, 0, 0.77]}
          rotation={[-0.06, -0.08, 0.01]}
          scale={0.04}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
