/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: futaba@blender (https://sketchfab.com/futaba_blender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/design-chair-373a09593d744d049f006ffa0b05b4d1
Title: Design Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TyrChair(props) {
  const { nodes, materials } = useGLTF('assets/Chairs/tyr_chair/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
