/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: furnny (https://sketchfab.com/furnny)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vitra-eames-plastic-chair-0a45955e2328459d95f403cb00c08b3a
Title: Vitra Eames Plastic Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VitraChair(props) {
  const { nodes, materials } = useGLTF('assets/Chairs/vitra_chair/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['01_-_Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['01_-_Default']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['01_-_Default']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['01_-_Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
