/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Watndit (https://sketchfab.com/Watndit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-sofa-62dbd2a0afb44b21ab43dcc936eb1d65
Title: Wooden Sofa
*/
import { useGLTF } from "@react-three/drei";

export function WoodenSofa(props) {
  const { nodes, materials } = useGLTF(
    "assets/Chairs/wooden_sofa/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.75}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Cube_rest_0.geometry}
            material={materials.rest}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={15.5}
          />
          <mesh
            geometry={nodes.Cube001_rest_0.geometry}
            material={materials.rest}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={15.5}
          />
          <mesh
            geometry={nodes.Cube002_rest_0.geometry}
            material={materials.rest}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={15.5}
          />
          <mesh
            geometry={nodes.Cube003_rest_0.geometry}
            material={materials.rest}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={15.5}
          />
          <group rotation={[-Math.PI / 2, 0, 0]} scale={15.5}>
            <mesh
              geometry={nodes.Cube004_leder_oben_0.geometry}
              material={materials.leder_oben}
            />
            <mesh
              geometry={nodes.Cube004_leder_oben_0_1.geometry}
              material={materials.leder_oben}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload('assets/Chairs/wooden_sofa/scene-transformed.glb.glb')


