/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sweep-floor-lamp-black-de6dc42e0fb44b4993ee58b4fda44daf
Title: Sweep Floor Lamp, Black
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -140.06, 168.71]} rotation={[-Math.PI, 0, 0]} scale={0.89}>
          <group position={[0, -0.03, -137.48]}>
            <mesh geometry={nodes.COPPER.geometry} material={materials.COPPER} />
            <mesh geometry={nodes.LIGHT_BULB.geometry} material={materials.EnvironmentAmbientLight} />
            <mesh geometry={nodes.STEEL_MATT_GREY.geometry} material={materials.STEEL_MATT_GREY} />
            <mesh geometry={nodes.RUBBER.geometry} material={materials.RUBBER} />
            <mesh geometry={nodes.STEEL.geometry} material={materials.STEEL} />
            <mesh geometry={nodes.STEEL_WHITE.geometry} material={materials.STEEL_WHITE} />
            <mesh geometry={nodes.LAMP_SHADE.geometry} material={materials.LAMP_SHADE} />
          </group>
        </group>
        <mesh geometry={nodes.FLOOR.geometry} material={materials.FLOOR} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
