/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Matt LeMoine (https://sketchfab.com/Matt_LeMoine)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/lamp-2b14055dc8054ec79b4d0d7e8f00be1e
Title: Lamp
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CirusLamp(props) {
  const { nodes, materials } = useGLTF(
    "assets/Lamps/cirus_lamp/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null} position={[0, 80, -300]}>
      <group position={[0, -196.27, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.pSphere4_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.pSphere4_lambert5_0.geometry}
              material={materials.lambert5}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
