/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: DuduPav (https://sketchfab.com/DuduPav)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-floor-lamp-free-4adc793119754406aa3bcd790782cd4c
Title: Wooden floor lamp. (FREE)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VelesLamp(props) {
  const { nodes, materials } = useGLTF(
    "assets/Lamps/veles_lamp/scene-transformed.glb"
  );
  return (
    <group
      {...props}
      dispose={null}
      position={[-1.5, -2, 0]}
      scale={0.0025}
      rotation={[Math.PI / 0.9, Math.PI, Math.PI]}
    >
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.M_10_Lamp_Wood}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.M_12_Plastic}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.M_12_Plastic}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.M_7_Metall}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.M_7_Metall}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.M_7_Metall}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.M_8_Lamp_Glass}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.M_8_Lamp_Glass}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.M_9_Lamp_Fabric5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
