/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: yryabchenko (https://sketchfab.com/yryabchenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-1132fa2850a24917892733566bd68e74
Title: Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder6_blinn1_0.geometry} material={materials.blinn1} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
